### ISSUE TITLE
Problems compiling the driver.

### ISSUE THREAD

**Issue by bastoi** [ebirbe/tlwn722n-linux-install#1]
Hi I tried to install the driver using your script, but without positive results, the install.sh and make commands, fail.

My linux distribution it's a Debian Wheezy (testing) and the output of the problem it's:

cat: [path_to_folder]/tlwn722n-linux-install-tlwn722n-linux-install-stable/compat-wireless-2012-05-10/.compat_version: El fitxer o directori no existeix
cat: [path_to_folder]/tlwn722n-linux-install-tlwn722n-linux-install-stable/compat-wireless-2012-05-10/.compat_base_tree: El fitxer o directori no existeix
cat: [path_to_folder]/tlwn722n-linux-install-tlwn722n-linux-install-stable/compat-wireless-2012-05-10/.compat_base_tree_version: El fitxer o directori no existeix
cat: [path_to_folder]/tlwn722n-linux-install-tlwn722n-linux-install-stable/compat-wireless-2012-05-10/.compat_version: El fitxer o directori no existeix
cat: [path_to_folder]/tlwn722n-linux-install-tlwn722n-linux-install-stable/compat-wireless-2012-05-10/.compat_version: El fitxer o directori no existeix
/bin/sh: 1: cannot create /home/joel/Baixades/tlwn722n-linux-install-tlwn722n-linux-install-stable/compat-wireless-2012-05-10/.config: Permission denied
make: **\* [[path_to_folder]/tlwn722n-linux-install-tlwn722n-linux-install-stable/compat-wireless-2012-05-10/.compat_autoconf_] Error 2

The problem i think that it's related with with the .gitignore file, because it's ignoring the folders that the make command it's unable to find.

P.D. The .config Permision problem, it's because i was launch first make as root, and this output it's as normal user. 

Thank's ;)

**Comment by lucaspalencia** [comment]
Hi! Same issue here with Ubuntu 14.10 64-bit. Any idea ?
