### ISSUE TITLE
implicit declaration of function idr_pre_get

### ISSUE THREAD

**Issue by michaelcalve** [ebirbe/tlwn722n-linux-install#3]
Hi, I'm currently attempting to install your drivers on a Raspberry Pi,

I manually installed the headers, and now I'm getting the error in the subject line from sudo ./install.sh

Any ideas as to what's happening?

Much appreciated!

**Comment by erickcion** [comment]
Hello @michaelcalve 

What's your kernel version?

**Comment by TrungSunbae** [comment]
Compiling modules...
make -C /lib/modules/4.4.0-57-generic/build M=/home/trunks/Desktop/tlwn722n-linux-install-latest/compat-drivers-source modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-57-generic'
/home/trunks/Desktop/tlwn722n-linux-install-latest/compat-drivers-source/config.mk:21: *** "ERROR: compat-drivers by default supports kernels >= 2.6.24, try enabling only one driver though".  Stop.
Makefile:1420: recipe for target '_module_/home/trunks/Desktop/tlwn722n-linux-install-latest/compat-drivers-source' failed
make[1]: *** [_module_/home/trunks/Desktop/tlwn722n-linux-install-latest/compat-drivers-source] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-57-generic'
Makefile:90: recipe for target 'modules' failed
make: *** [modules] Error 2
There was a problem compiling the package.
trunks@trunks-Aspire-VN7-791:~/Desktop/tlwn722n-linux-install-latest$ 


HI! im new to linux ubuntu, trying to learn a thing or two about this stuff. 
I have installed the headers just like the readme directed and executed the following commands 
$ cd unzipped_folder_name
$ chmod +x ./install.sh
$ su root -c ./install.sh

**Comment by ebirbe** [comment]
> HI! im new to linux ubuntu, trying to learn a thing or two about this stuff.
> I have installed the headers just like the readme directed and executed the following commands

Hello @TrungSunbae I think you don't need this driver. Your kernel version is greater than 3.0.

This script will not work for your kernel. In fact, TLWN722N wireless devices usually work fine, without any additional step to do on Linux distributions with kernel versions greater than 3.2
