### ISSUE TITLE
Issue on Kali during install

### ISSUE THREAD

**Issue by milan359** [ebirbe/tlwn722n-linux-install#4]
"maybe" I do something wrong but this don't work on Kali roling or is it issue that I did previously download of compact for wireless...  
Maybe this installation log help 
/usr/src/linux-headers-4.9.0-kali3-common/include/linux/phy.h:362:21: error: field ‘mdio’ has incomplete type
  struct mdio_device mdio;
                     ^~~~
/usr/src/linux-headers-4.9.0-kali3-common/include/linux/phy.h:456:28: error: field ‘mdiodrv’ has incomplete type
  struct mdio_driver_common mdiodrv;
                            ^~~~~~~
/usr/src/linux-headers-4.9.0-kali3-common/include/linux/phy.h: In function ‘phy_read_mmd’:
/usr/src/linux-headers-4.9.0-kali3-common/include/linux/phy.h:622:9: error: implicit declaration of function ‘mdiobus_read’ [-Werror=implicit-function-declaration]
  return mdiobus_read(phydev->mdio.bus, phydev->mdio.addr,
         ^~~~~~~~~~~~
/usr/src/linux-headers-4.9.0-kali3-common/include/linux/phy.h: In function ‘phy_write’:
/usr/src/linux-headers-4.9.0-kali3-common/include/linux/phy.h:663:9: error: implicit declaration of function ‘mdiobus_write’ [-Werror=implicit-function-declaration]
  return mdiobus_write(phydev->mdio.bus, phydev->mdio.addr, regnum, val);
         ^~~~~~~~~~~~~
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.9.0-kali3-common/scripts/Makefile.build:298: recipe for target '/root/Downloads/tlwn722n-linux-install/compat-drivers-source/compat/main.o' failed
make[5]: *** [/root/Downloads/tlwn722n-linux-install/compat-drivers-source/compat/main.o] Error 1
/usr/src/linux-headers-4.9.0-kali3-common/scripts/Makefile.build:549: recipe for target '/root/Downloads/tlwn722n-linux-install/compat-drivers-source/compat' failed
make[4]: *** [/root/Downloads/tlwn722n-linux-install/compat-drivers-source/compat] Error 2
/usr/src/linux-headers-4.9.0-kali3-common/Makefile:1507: recipe for target '_module_/root/Downloads/tlwn722n-linux-install/compat-drivers-source' failed
make[3]: *** [_module_/root/Downloads/tlwn722n-linux-install/compat-drivers-source] Error 2
Makefile:150: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.0-kali3-amd64'
Makefile:90: recipe for target 'modules' failed
make: *** [modules] Error 2
There was a problem compiling the package.

I starting to believe that I will not manage to make this wi-fi USB to work.
Thank you in advance in any case

**Comment by ericraio** [comment]
+1 I have the same issue :(
