### ISSUE TITLE
Issue on Ubuntu

### ISSUE THREAD

**Issue by buonoca** [ebirbe/tlwn722n-linux-install#5]
Hello, I cannot for the life of me get the TP Link WN722N to install in Ubuntu 17.04.

I have followed the instructions and gee following output:

Installing firware...

Changing to directory "compat-drivers-source"...
Trying to select the ath9k_htc diver to be compiled...
Processing new driver-select request...
Backing up makefile: Makefile.bk
Backup exists: Makefile.bk
Backup exists: Makefile.bk
Backup exists: Makefile.bk
Backup exists: Makefile.bk
Backing up makefile: drivers/net/wireless/Makefile.bk
Backing up makefile: drivers/net/wireless/ath/Makefile.bk
Backing up makefile: net/wireless/Makefile.bk
Backing up makefile: drivers/ssb/Makefile.bk
Backing up makefile: drivers/bcma/Makefile.bk
Backing up makefile: drivers/misc/eeprom/Makefile.bk
Backup exists: Makefile.bk
Compiling modules...
./scripts/gen-compat-autoconf.sh /home/user/Downloads/tlwn722n-linux-install-master/compat-drivers-source/.config /home/user/Downloads/tlwn722n-linux-install-master/compat-drivers-source/config.mk > include/linux/compat_autoconf.h
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
sed: character class syntax is [[:space:]], not [:space:]
make -C /lib/modules/4.10.0-20-generic/build M=/home/user/Downloads/tlwn722n-linux-install-master/compat-drivers-source modules
make[1]: Entering directory '/usr/src/linux-headers-4.10.0-20-generic'
/home/user/Downloads/tlwn722n-linux-install-master/compat-drivers-source/config.mk:21: *** "ERROR: compat-drivers by default supports kernels >= 2.6.24, try enabling only one driver though". Stop.
Makefile:1524: recipe for target '_module_/home/user/Downloads/tlwn722n-linux-install-master/compat-drivers-source' failed
make[1]: *** [_module_/home/user/Downloads/tlwn722n-linux-install-master/compat-drivers-source] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.10.0-20-generic'
Makefile:90: recipe for target 'modules' failed
make: *** [modules] Error 2
There was a problem compiling the package.
t th

Any clues?

**Comment by Seminioni** [comment]
Hey @buonoca did you solved your problem?

**Comment by ebirbe** [comment]
It's normal that it does not work for your Ubuntu version, since this script will only work for Linux kernel versions prior to 3.0

**Comment by Seminioni** [comment]
Oh thanks @ebirbe for your reply! 
I've already solved my problem following guide from this repo https://github.com/lwfinger/rtl8188eu
